sudo: required

services:
  - docker

language: scala

before_install:
 - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

script: "sbt clean coverage test"

after_success:
 - sbt coveralls
 - sbt docker
